services:
  web:
    container_name: web.todovestwell
    build:
      context: .
      dockerfile: ./todofrontvestwell/Dockerfile
    depends_on:
      - back
    ports:
      - 4200:4200

  back:
    container_name: back.todovestwell
    build:
      context: .
      dockerfile: ./todo-back-vestwell/Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db.todovestwell
    image: mysql
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=todovestwell123
      - MYSQL_DATABASE=todovestwell
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
