services:
  web:
    container_name: web.todovestwell
    build:
      context: .
      dockerfile: ./todofrontvestwell/Dockerfile
    ports:
      - 4200:4200
    environment:
      - PORT=4200
      - NODE_ENV=development
    volumes:
      - ./todofrontvestwell:/src/app
    depends_on:
      - back
    networks:
      - todo-network

  back:
    container_name: back.todovestwell
    build:
      context: .
      dockerfile: ./todo-back-vestwell/Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./todo-back-vestwell/src:/app/nestjs/src
    depends_on:
      - mysql_db
    networks:
      - todo-network

  mysql_db:
    container_name: mysql_db.todovestwell
    image: mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
