import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import theme from "../theme";
import "./globals.css";
import { HandleErrorsProvider } from "@/providers/handleErrorsProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import HandleQueryProvider from "@/providers/handleQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HandleQueryProvider>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <HandleErrorsProvider>{children}</HandleErrorsProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </HandleQueryProvider>
      </body>
    </html>
  );
}
